### PR TITLE
Fix helpUrl for all occurences

### LINKED ISSUE #122: default doc url now points to inexistant page
https://github.com/georchestra/mapstore2-cadastrapp/blob/ae71948e206c188fbde35417e495f103c76f58e1/assets/index.json#L9 points https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur which was removed and was about the mfapp version of the doc, now it should be https://docs.georchestra.org/cadastrapp/latest/guide_utilisateur/ per georchestra/cadastrapp#564

### PR DESCRIPTION
**Pull request by landryb**
(Re-)Fixes #122

### CODE REVIEW

**Comment by landryb** [comment]
dammit, wasnt on master.

**Comment by landryb** [comment]
something is still wrong/puzzling somewhere, as i enabled cadastrapp in the default context (eg just adding "Cadastrapp" to the list of plugins in `localConfig.json`) and it still points to the old url https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur. 

even if `pluginsConfig.json.patch` has the right url.. should that patch/file be the default config for the plugin ?
```
[{"op":"add","path":"/plugins/-","value":{"name":"Cadastrapp","glyph":"th","docUrl":"https://github.com/georchestra/mapstore2-cadastrapp#plugin-configuration","defaultConfig":{"helpUrl":"https://docs.georchestra.org/cadastrapp/latest/guide_utilisateur/","foncier":true,"popu
p":{"minZoom":14,"timeToShow":1000}},"dependencies":["BurgerMenu"],"extension":true}}]

```

**Comment by landryb** [comment]
afaict after testing, the `helpUrl` used when the plugin is just enabled in `localConfig.json` is the one fixed by cf34b54.

**Review by MaelREBOUX — APPROVED** [review]
I approve

**Comment by MaelREBOUX** [comment]
@tdipisa could we merge this PR : it is totally minor for code but important for our users ?

**Review by tdipisa — APPROVED** [review]

**Comment by tdipisa** [comment]
@offtherailz please provide an RC including this update. Thank you.

**Pull request merged**
