### PR TITLE
use the right WFS layer name when querying the WFS service

### PR DESCRIPTION
**Pull request by landryb**

### CODE REVIEW

**Review by offtherailz — COMMENTED** [review]
@landryb I think we have the same in the 'search' epic, when we retrieve the feaures for search each result. 

https://github.com/georchestra/mapstore2-cadastrapp/blob/ab1d89275eb41ab9fe414d9687403204d7b98c78/js/extension/epics/search.js#L164

**Comment by offtherailz** [comment]
It should be enough, tomorrow I'll check and try finalize this part. I'll also check the part with UF URL.

**Comment by landryb** [comment]
> @landryb I think we have the same in the 'search' epic, when we retrieve the feaures for search each result.
> 
> https://github.com/georchestra/mapstore2-cadastrapp/blob/ab1d89275eb41ab9fe414d9687403204d7b98c78/js/extension/epics/search.js#L164

you're right, clicking/selecting a plot works, but searching a plot by reference or owner produces the same error.

**Comment by landryb** [comment]
9ab0eaf fixed that, tested both by searching by owner and by plot reference

**Review by offtherailz — APPROVED** [review]
Great! thank you :+1:

**Pull request merged**
