### PR TITLE
Exporting selected plots into annotation

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
Exporting selected plots into annotation

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
Hi @alexander-fedorenko 
LGTM.

Just a minor enhancement,
I think we can disable the `Save as Annotation` when no plot are selected

**Steps to reproduce**:
1. Select some plots
2. And delete those from the `Plot selection` grid 
3. Now user can click on `Save as annotation` which opens annotation panel to add new annotation

image

**Comment by alexander-fedorenko** [comment]
Thanks @dsuren1 
Corrected this behavior by adding disabled state if no plots in the list.

**Review by dsuren1 — APPROVED** [review]

**Comment by landryb** [comment]
fwiw, i've tested the feature and it works fine. It's a bit convoluted to explain end-users that they have to 'save as annotation' then 'save again in the annotation pane' if they want to print the map with their selection (since they see them, they don't understand why printing as is wont print them too)... but via the annotation trick the selected plots are in the resulting pdf.

**Comment by tdipisa** [comment]
@landryb 

>fwiw, i've tested the feature and it works fine. It's a bit convoluted to explain end-users that they have to 'save as annotation' then 'save again in the annotation pane' if they want to print the map with their selection (since they see them, they don't understand why printing as is wont print them too)... but via the annotation trick the selected plots are in the resulting pdf.

"Save as annotation" is an additional functionality requested. You don't need to use it to print the plot selection. We have included the sidebar to be effectively able to use other tools while cadastrapp is open, right? There is a new option in the printing preview you can check to include in the final print also the overlays like the plot selection.

2022_06_24_17_40_11_Window

**Comment by landryb** [comment]
> @landryb
> 
> > fwiw, i've tested the feature and it works fine. It's a bit convoluted to explain end-users that they have to 'save as annotation' then 'save again in the annotation pane' if they want to print the map with their selection (since they see them, they don't understand why printing as is wont print them too)... but via the annotation trick the selected plots are in the resulting pdf.
> 
> "Save as annotation" is an additional functionality requested. You don't need to use it to print the plot selection. We have included the sidebar to be effectively able to use other tools while cadastrapp is open, right? There is a new option in the printing preview you can check to include in the final print also the overlays like the plot selection.

Oh right, sorry i totally overlooked that. Thanks a lot for the explanation :)

**Pull request merged**
