### PR TITLE
remove duplicated quote to remove underscore create by browser

### PR DESCRIPTION
**Pull request by pierrejego**
Link to https://github.com/georchestra/cadastrapp/issues/615 and #143 

Tested on gis.jdev.fr environnement

### CODE REVIEW

**Review by jusabatier — APPROVED** [review]

**Comment by MaelREBOUX** [comment]
👍

**Review by tdipisa — CHANGES_REQUESTED** [review]
I've tried to reproduce this on our DEV instance [here](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp) where we are using the last version of the extensions (eg. cadastrapp in this case). As far as I can see, I'm not able to reproduce this issue.

Is the use case depicted in the GIF below correct @pierrejego? Otherwise can you kindly indicate it?

csv_file

I've tested the use case above on the following browsers (versions of browsers are the last ones available):

Chrome: 99.0.4844.74 
FF: 98.0.1 
Edge: 99.0.1150.46

However, if in some cases this issue exists, directly forcing a replacement I'm not sure is the right fix do. We should at least understand why these wrong characters are present in the file name instead.

I will ask developers (@dsuren1 and @offtherailz) to do a check on this as soon as the use case to reproduce is confirmed or clarified.

Which browser versions are you using?

**Comment by catmorales** [comment]
For the "_" , use case is decribed in https://github.com/georchestra/cadastrapp/issues/615.
However, il will update mapstore2-georchestra, mapstore2-cadastrapp  and cadastrapp to test with the latest versions of both.

**Comment by tdipisa** [comment]
@catmorales are you able to reproduce the same using [the context in our DEV instance](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp)?

**Comment by catmorales** [comment]
>@catmorales are you able to reproduce the same using [the context in our DEV instance](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp)?

yes i reproduce the "_" on chrome, i  have updated all this morning in portail-test

Cadastrapp (BE) --> Cadastrapp V2.0
Mapstore2-cadastrapp --> rc18
Mapstore2-georchestra --> 21.02.xx (image docker geosolutions)

**Comment by catmorales** [comment]
To clarify i will give you details and uses cases on:
* https://github.com/georchestra/cadastrapp/issues/615  fr the "_" added by  chrome
* https://github.com/georchestra/mapstore2-cadastrapp/issues/153 for the extension "txt" instead of "csv" by  firefox

**Comment by pierrejego** [comment]
Hi @tdipisa ,
this problem came only with new backend. We have changed technologie from Jaxrs to SpringMVC. this made a change on headers. He have additionnal quote " in filename field.
This is ok with rfc http https://www.rfc-editor.org/rfc/rfc6266 but not managed with Chrome Engine which replace quote (and special chars) by underscore _
This PR is just made to remove those chars so we don't have any underscore.

We have discuss about it yesterday afternoon with Catherine, Those few change won't have any impact on current version. I therefore allow myself to merge the PR. Do not hesitate to contact me if needed

Regards

**Comment by tdipisa** [comment]
> Hi @tdipisa , this problem came only with new backend. We have changed technologie from Jaxrs to SpringMVC. this made a change on headers. He have additionnal quote " in filename field. This is ok with rfc http https://www.rfc-editor.org/rfc/rfc6266 but not managed with Chrome Engine which replace quote (and special chars) by underscore _ This PR is just made to remove those chars so we don't have any underscore.
> 
> We have discuss about it yesterday afternoon with Catherine, Those few change won't have any impact on current version. I therefore allow myself to merge the PR. Do not hesitate to contact me if needed
> 
> Regards

Dear @pierrejego ok. In my opinion we should better keep track of this at least by putting a comment in the code for future reference including also the link to this PR and maybe also a link to a new issue aimed to investigate the root cause of the problem for a definitive fix.

**Comment by landryb** [comment]
> In my opinion we should better keep track of this at least by putting a comment in the code for future reference including also the link to this PR and maybe also a link to a new issue aimed to investigate the root cause of the problem for a definitive fix.

from my understanding there's no other "definitive fix", the root cause is identified: underlying libraries changed, adding the quotes is the behaviour of the new library upon which we have no control, so things will be this way and have to be dealt with. The commit doesn't break compatibility with previous versions (filenames are generated by the backend and cant contain user-generate strings so no risk of having " or ' in there), so things are safe for users using the older backend (as you witnessed since you didnt manage to reproduce the issue) - if you update the plugin/client side on your install things will still work as before.

as for putting comments, i think everything is properly "documented" in commit messages which link back to this PR which has all the references needed for related issues.

**Pull request merged**
